server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, MobileHub-Gateway

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8088"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # === Identity Service ===
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**, /api/identity/**

        # === User Service ===
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        # === Product Service ===
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**, /api/categories/**

        # === Cart Service ===
        - id: cart-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/cart/**

        # === Order Service ===
        - id: order-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/orders/**

        # === Cloud Media Service ===
        - id: cloud-media-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/media/**

      discovery:
        locator:
          enabled: false
