server:
  port: 8080

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # === Identity Service ===
        - id: identity_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/auth/**
            #- Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        # === User Service ===
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/users/**
          filters:
            - StripPrefix=2

        # === Product Service ===
        - id: product_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/products/**, ${app.api-prefix}/categories/**
          filters:
            - StripPrefix=2

        # === Cart Service ===
        - id: cart_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/cart/**
          filters:
            - StripPrefix=2

        # === Order Service ===
        - id: order_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=2

        # === Cloud Media Service ===
        - id: cloud_media_service
          uri: http://localhost:8090
          predicates:
            - Path=${app.api-prefix}/media/**
          filters:
            - StripPrefix=2

      discovery:
        locator:
          enabled: false
