spring:
  application:
    name: installment-service
  config:
    import: "optional:configserver:http://localhost:8888"

# Service URLs
services:
  identity:
    url: ${IDENTITY_SERVICE_URL:http://localhost:8081}
