server:
  port: 8082                  # Port

spring:
  spring:
    application:
      name: customer-service

  datasource:
    url: jdbc:mysql://localhost:3306/mobilehub_customer?createDatabaseIfNotExist=true
    username: root
    password: root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

service:
  identity: http://localhost:8081